### ISSUE TITLE
不支持展开运算符的写法，怎么配置呢？

### ISSUE THREAD

**Issue by zuijiaoluo** [bramblex/nwjs-vue#1]
@bramblex 
![image](https://cloud.githubusercontent.com/assets/22735208/22022260/2b942b76-dcfc-11e6-8f14-7645c58ab18b.png)

**Comment by bramblex** [comment]
这个是 babel 配置的锅，可能是旧版本 vue-template 的 babel 配置有问题，我会在近段时间把这个问题给修复了。如果你急用的话，这里又个简单的处理方法能解决。

1. 首先更改 .babel.rc 文件
``` JavaScript
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

2.安装 es2015 preset
``` Bash
npm install --save-dev  babel-preset-es2015 babel-preset-stage-2
```

然后应该能正常运行了

**Comment by zuijiaoluo** [comment]
嗯嗯  这个我今天也是这样改的  不过这个配置还是有很多需要加的   明天公司年会   过完年会可以一起研究下   

![image](https://cloud.githubusercontent.com/assets/22735208/22067430/2daa3cae-ddcc-11e6-9c29-d42079faa1e3.png)


还有这个问题我也一直不明白  虽然不影响使用  @bramblex

**Comment by bramblex** [comment]
这个不记得是引入 vue-devtools 还是用 remote 调试才会会出现的问题，只会在调试的时候出现，build 后的不会出现这个问题。具体原因还不明，但是暂时没发现影响使用的问题。
