### ISSUE TITLE
不支持vue-router的跳转

### ISSUE THREAD

**Issue by zuijiaoluo** [bramblex/nwjs-vue#2]
![image](https://cloud.githubusercontent.com/assets/22735208/22357728/0ec07d76-e475-11e6-8e03-fe38b3f5ccad.png)

**Comment by bramblex** [comment]
我默认里面就有 vue-router /w\

demo 里面的标签页就是 vue-router 实现的呀

**Comment by zuijiaoluo** [comment]
可以跳转的  是vue－element的版本问题，导致报错的，
现在我正在打包呢，直接用你的这个demo是可以的  但是自己的就不行了，
有一个包报错，应该是webpack没有配置好，我注释掉了，
然后打完包发现是空白的，有没有办法打包以后，在那个上面开f12

**Comment by zuijiaoluo** [comment]
通过这个  var win = nw.Window.get();
    win.showDevTools()
调用出来的也是空白的调试f12
![image](https://cloud.githubusercontent.com/assets/22735208/22361155/f5ec4be6-e491-11e6-9400-3787df3a7158.png)

**Comment by bramblex** [comment]
对了，config/vue-packes里面需要标注哪些是需要webpack打包的。

build/nwbuild.js build 配置项的 flavor 改成sdk 就可以打开用 sdk 打包调试了

新年快乐～
